import { ThemeProvider } from '../components/ui/theme-provider'
import ModeToggle from './Home/page'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}




export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div
              className="absolute top-0 right-0 m-4"

            >
              <ModeToggle />

            </div>

            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}
